### ISSUE TITLE
some icons on landscape iPhones are cut on some devices

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-app#167]
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-01-21 at 16 45 41-down](https://user-images.githubusercontent.com/1942953/105375366-f1bb2680-5c08-11eb-9753-50497f375dba.png)

**Comment by SoleCincis** [comment]
### After some test on available devices I can conclude that this bug is present on landscape screens with a height between  67.3 mm - 77.8 mm

iPhone SE ( 4-inch, horizontal height 58.6 mm, width 123.8 mm - smallest screen that I can test on )  
(!) **No issues** 
![IMG_20E83162DFB6-1](https://user-images.githubusercontent.com/43641321/106285222-80045d80-6244-11eb-9c3c-b2ab915ce116.jpeg)
iPhone SE 2nd generation  (  4.7-inch, horizontal height 67.3 mm, width 138.4 mm ) 
**slightly cropped icon**
![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-01-29 at 15 44 47](https://user-images.githubusercontent.com/43641321/106291105-81855400-624b-11eb-8158-701facfc4edc.png)
iPhone 8 ( 4.7-inch, horizontal height 67.3 mm, width 138.4 mm ) 
**slightly cropped icon**
![iPhone 8 - ](https://user-images.githubusercontent.com/43641321/106285996-729ba300-6245-11eb-8732-a421b52733cd.png)
iPhone 8Plus ( 5.5-inch, horizontal height 78.1 mm, width 158.4 mm ) 
**partially cropped icon**
![Simulator Screen Shot - iPhone 8 Plus - 2021-01-29 at 15 21 03](https://user-images.githubusercontent.com/43641321/106286306-c9a17800-6245-11eb-9cec-dc245485c9a4.png)
 iPhone 11 Pro Max ( 6.5-inch, horizontal height 77.8 mm,  width 158.0 mm ) 
**partially cropped icon**
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-01-29 at 15 23 45](https://user-images.githubusercontent.com/43641321/106291760-50595380-624c-11eb-9ad2-0542078a46ac.png)
iPad Pro (9.7-inch, horizontal height 169.5 mm, width 240 mm - smallest iPad screen that I can test on)
(!) **No issues** 
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-01-29 at 15 41 09](https://user-images.githubusercontent.com/43641321/106293235-0c674e00-624e-11eb-8370-bd2f25a0c2a0.png)
 iPad Pro (12.9-inch,  horizontal height 214.9 mm, width 280.6 mm - biggest iPad screen that I can test on) 
(!) **No issues** 
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2021-01-29 at 15 25 33](https://user-images.githubusercontent.com/43641321/106293390-3fa9dd00-624e-11eb-8832-45aeecc660e8.png)
